//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHGPDFCsharp.BHGService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BHGService.IBHGService")]
    public interface IBHGService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBHGService/GetForms1846_BAL", ReplyAction="http://tempuri.org/IBHGService/GetForms1846_BALResponse")]
        System.Data.DataSet GetForms1846_BAL(string strStartDate, string strEndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBHGService/GetForms1624_BAL", ReplyAction="http://tempuri.org/IBHGService/GetForms1624_BALResponse")]
        System.Data.DataSet GetForms1624_BAL(string strStartDate, string strEndDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBHGServiceChannel : BHGPDFCsharp.BHGService.IBHGService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BHGServiceClient : System.ServiceModel.ClientBase<BHGPDFCsharp.BHGService.IBHGService>, BHGPDFCsharp.BHGService.IBHGService {
        
        public BHGServiceClient() {
        }
        
        public BHGServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BHGServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BHGServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BHGServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetForms1846_BAL(string strStartDate, string strEndDate) {
            return base.Channel.GetForms1846_BAL(strStartDate, strEndDate);
        }
        
        public System.Data.DataSet GetForms1624_BAL(string strStartDate, string strEndDate) {
            return base.Channel.GetForms1624_BAL(strStartDate, strEndDate);
        }
    }
}
